"""initial schema

Revision ID: 023f438ecf73
Revises: 
Create Date: 2026-07-11 13:19:53.267769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '023f438ecf73'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peril',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('policy_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insurer', sa.String(), nullable=False),
    sa.Column('product', sa.String(), nullable=False),
    sa.Column('susep_process', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('property_type', sa.String(), nullable=True),
    sa.Column('pdf_url', sa.String(), nullable=False),
    sa.Column('pdf_hash', sa.String(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('susep_process', 'version')
    )
    op.create_table('coverage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('coverage_name', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('deductible_type', sa.String(), nullable=True),
    sa.Column('deductible_rule_text', sa.String(), nullable=True),
    sa.CheckConstraint("deductible_type IN ('none', 'percentage', 'fixed_amount', 'defined_in_policy')", name='ck_coverage_deductible_type'),
    sa.CheckConstraint("kind IN ('basic', 'additional')", name='ck_coverage_kind'),
    sa.ForeignKeyConstraint(['document_id'], ['policy_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coverage_peril',
    sa.Column('coverage_id', sa.Integer(), nullable=False),
    sa.Column('peril_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coverage_id'], ['coverage.id'], ),
    sa.ForeignKeyConstraint(['peril_id'], ['peril.id'], ),
    sa.PrimaryKeyConstraint('coverage_id', 'peril_id')
    )
    op.create_table('exclusion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('coverage_id', sa.Integer(), nullable=True),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('clause_text', sa.String(), nullable=False),
    sa.CheckConstraint("(scope = 'general' AND coverage_id IS NULL) OR (scope = 'coverage' AND coverage_id IS NOT NULL)", name='ck_exclusion_scope_coverage_id'),
    sa.CheckConstraint("scope IN ('general', 'coverage')", name='ck_exclusion_scope'),
    sa.ForeignKeyConstraint(['coverage_id'], ['coverage.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['policy_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exclusion')
    op.drop_table('coverage_peril')
    op.drop_table('coverage')
    op.drop_table('policy_document')
    op.drop_table('peril')
    # ### end Alembic commands ###
