"""add coverage.plan

Revision ID: 485fa9753a4c
Revises: 023f438ecf73
Create Date: 2026-07-14 12:34:05.249367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '485fa9753a4c'
down_revision: Union[str, Sequence[str], None] = '023f438ecf73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coverage', sa.Column('plan', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coverage', 'plan')
    # ### end Alembic commands ###
