"""add request_id and client to cost_event

Revision ID: 91956643f279
Revises: 4b285ffad59b
Create Date: 2026-07-29 16:03:18.528144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91956643f279'
down_revision: Union[str, Sequence[str], None] = '4b285ffad59b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Correlação de custo por request e por cliente.

    NULLABLE de propósito, e sem backfill: as linhas antigas são da extração offline,
    onde não existe request nem cliente. NULL aqui significa "chamada fora de um
    request" — inventar um valor apagaria essa distinção.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cost_event', sa.Column('request_id', sa.String(), nullable=True))
    op.add_column('cost_event', sa.Column('client', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cost_event', 'client')
    op.drop_column('cost_event', 'request_id')
    # ### end Alembic commands ###
